resolvers += MavenRepository("HMRC-maven2", "https://open.artefacts.tax.service.gov.uk/maven2")
resolvers += Resolver.url("HMRC-ivy2", url("https://open.artefacts.tax.service.gov.uk/ivy2"))(Resolver.ivyStylePatterns)

addSbtPlugin("uk.gov.hmrc"        % "sbt-auto-build"     % "3.22.0")
addSbtPlugin("uk.gov.hmrc"        % "sbt-distributables" % "2.5.0")
addSbtPlugin("org.playframework"  % "sbt-plugin"         % "3.0.5")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"      % "2.1.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"       % "0.12.1")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"    % "3.1.8")
addSbtPlugin("io.github.irundaia" % "sbt-sassify"        % "1.5.2")
addSbtPlugin("com.github.sbt"     % "sbt-digest"         % "2.0.0")
addSbtPlugin("com.github.sbt"     % "sbt-concat"         % "1.0.0")
