addSbtPlugin("org.playframework"  % "sbt-plugin"      % "3.0.4")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "2.1.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"    % "0.12.1")
addSbtPlugin("org.wartremover"    % "sbt-wartremover" % "3.1.6")
addSbtPlugin("io.github.irundaia" % "sbt-sassify"     % "1.5.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-digest"      % "1.1.4")
addSbtPlugin("com.github.sbt"     % "sbt-concat"      % "1.0.0")
